### ISSUE TITLE
scala.tools.reflect.ToolBoxError: reflective compilation has failed

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/commons#91]
```
09:51:44   [INFO] object transform is not a member of package za.co.absa.spark.hofs
09:51:44   [INFO]   at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.throwIfErrors(ToolBoxFactory.scala:316)
09:51:44   [INFO]   at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.wrapInPackageAndCompile(ToolBoxFactory.scala:198)
09:51:44   [INFO]   at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.compile(ToolBoxFactory.scala:252)
09:51:44   [INFO]   at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$$anonfun$compile$2.apply(ToolBoxFactory.scala:429)
09:51:44   [INFO]   at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$$anonfun$compile$2.apply(ToolBoxFactory.scala:422)
09:51:44   [INFO]   at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.liftedTree2$1(ToolBoxFactory.scala:355)
09:51:44   [INFO]   at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.apply(ToolBoxFactory.scala:355)
09:51:44   [INFO]   at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.compile(ToolBoxFactory.scala:422)
09:51:44   [INFO]   at za.co.absa.commons.reflect.ReflectionUtils$.compile(ReflectionUtils.scala:46)
09:51:44   [INFO]   at za.co.absa.commons.spark.HofsAdapter$class.$init$(HofsAdapter.scala:39)
```

The error is presumable caused by the long-standing Scala bug scala/bug#6393

**Comment by wajda** [comment]
As agreed with @Zejnilovic and @benedeki we can get rid of entire `spark` package, eliminating the need of HOFS (that triggers the aforementioned Scala bug) and making the Commons dependency tree consistent (with respect to binary compatibility) across all Scala cross-compiled variants.
